wget https://huggingface.co/jetmoe/jetmoe-8b/resolve/main/config.json
wget https://huggingface.co/jetmoe/jetmoe-8b/resolve/main/generation_config.json
wget https://huggingface.co/jetmoe/jetmoe-8b/resolve/main/model-00001-of-00004.safetensors
wget https://huggingface.co/jetmoe/jetmoe-8b/resolve/main/model-00002-of-00004.safetensors
wget https://huggingface.co/jetmoe/jetmoe-8b/resolve/main/model-00003-of-00004.safetensors
wget https://huggingface.co/jetmoe/jetmoe-8b/resolve/main/model-00004-of-00004.safetensors
wget https://huggingface.co/jetmoe/jetmoe-8b/resolve/main/model.safetensors.index.json
wget https://huggingface.co/jetmoe/jetmoe-8b/resolve/main/README.md
wget https://huggingface.co/jetmoe/jetmoe-8b/resolve/main/special_tokens_map.json
wget https://huggingface.co/jetmoe/jetmoe-8b/resolve/main/tokenizer_config.json
wget https://huggingface.co/jetmoe/jetmoe-8b/resolve/main/tokenizer.json
wget https://huggingface.co/jetmoe/jetmoe-8b/resolve/main/tokenizer.model
